// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace EVRental.SoapServices.QuanNH.SoapModels;

[DataContract]
public partial class CheckOutQuanNh
{
    [DataMember]
    public int CheckOutQuanNhid { get; set; }
    [DataMember]
    public DateTime? CheckOutTime { get; set; }
    [DataMember]
    public DateTime? ReturnDate { get; set; }
    [DataMember]
    public decimal? ExtraCost { get; set; }
    [DataMember]
    public decimal? TotalCost { get; set; }
    [DataMember]
    public decimal? LateFee { get; set; }
    [DataMember]
    public bool IsPaid { get; set; }
    [DataMember]
    public bool IsDamageReported { get; set; }
    [DataMember]
    public string Notes { get; set; }
    [DataMember]
    public string CustomerFeedback { get; set; }
    [DataMember]
    public string PaymentMethod { get; set; }
    [DataMember]
    public string StaffSignature { get; set; }
    [DataMember]
    public string CustomerSignature { get; set; }
    [DataMember]
    public int? ReturnConditionId { get; set; }
    [DataMember]
    public virtual ReturnCondition ReturnCondition { get; set; }
}