// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace EVRental.SoapServices.QuanNH.SoapModels;

[DataContract]
public partial class ReturnCondition
{
    [DataMember]
    public int ReturnConditionId { get; set; }
    [DataMember]
    public string Name { get; set; }
    [DataMember]
    public int? SeverityLevel { get; set; }
    [DataMember]
    public decimal? RepairCost { get; set; }
    [DataMember]
    public bool? IsResolved { get; set; }
    [DataMember]
    public virtual CheckOutQuanNh CheckOutQuanNh { get; set; }
}