//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVRentalWCFServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckOutQuanNh", Namespace="http://schemas.datacontract.org/2004/07/EVRental.SoapServices.QuanNH.SoapModels")]
    public partial class CheckOutQuanNh : object
    {
        
        private int CheckOutQuanNhidField;
        
    private System.Nullable<System.DateTime> CheckOutTimeField;
        
        private string CustomerFeedbackField;
        
        private string CustomerSignatureField;
        
        private System.Nullable<decimal> ExtraCostField;
        
        private bool IsDamageReportedField;
        
        private bool IsPaidField;
        
        private System.Nullable<decimal> LateFeeField;
        
        private string NotesField;
        
        private string PaymentMethodField;
        
        private EVRentalWCFServiceReference.ReturnCondition ReturnConditionField;
        
        private System.Nullable<int> ReturnConditionIdField;
        
    private System.Nullable<System.DateTime> ReturnDateField;
        
        private string StaffSignatureField;
        
        private System.Nullable<decimal> TotalCostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CheckOutQuanNhid
        {
            get
            {
                return this.CheckOutQuanNhidField;
            }
            set
            {
                this.CheckOutQuanNhidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CheckOutTime
        {
            get
            {
                return this.CheckOutTimeField;
            }
            set
            {
                this.CheckOutTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFeedback
        {
            get
            {
                return this.CustomerFeedbackField;
            }
            set
            {
                this.CustomerFeedbackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSignature
        {
            get
            {
                return this.CustomerSignatureField;
            }
            set
            {
                this.CustomerSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtraCost
        {
            get
            {
                return this.ExtraCostField;
            }
            set
            {
                this.ExtraCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDamageReported
        {
            get
            {
                return this.IsDamageReportedField;
            }
            set
            {
                this.IsDamageReportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPaid
        {
            get
            {
                return this.IsPaidField;
            }
            set
            {
                this.IsPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LateFee
        {
            get
            {
                return this.LateFeeField;
            }
            set
            {
                this.LateFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVRentalWCFServiceReference.ReturnCondition ReturnCondition
        {
            get
            {
                return this.ReturnConditionField;
            }
            set
            {
                this.ReturnConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReturnConditionId
        {
            get
            {
                return this.ReturnConditionIdField;
            }
            set
            {
                this.ReturnConditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> ReturnDate
        {
            get
            {
                return this.ReturnDateField;
            }
            set
            {
                this.ReturnDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffSignature
        {
            get
            {
                return this.StaffSignatureField;
            }
            set
            {
                this.StaffSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCondition", Namespace="http://schemas.datacontract.org/2004/07/EVRental.SoapServices.QuanNH.SoapModels")]
    public partial class ReturnCondition : object
    {
        
        private EVRentalWCFServiceReference.CheckOutQuanNh CheckOutQuanNhField;
        
        private System.Nullable<bool> IsResolvedField;
        
        private string NameField;
        
        private System.Nullable<decimal> RepairCostField;
        
        private int ReturnConditionIdField;
        
        private System.Nullable<int> SeverityLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVRentalWCFServiceReference.CheckOutQuanNh CheckOutQuanNh
        {
            get
            {
                return this.CheckOutQuanNhField;
            }
            set
            {
                this.CheckOutQuanNhField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsResolved
        {
            get
            {
                return this.IsResolvedField;
            }
            set
            {
                this.IsResolvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RepairCost
        {
            get
            {
                return this.RepairCostField;
            }
            set
            {
                this.RepairCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnConditionId
        {
            get
            {
                return this.ReturnConditionIdField;
            }
            set
            {
                this.ReturnConditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SeverityLevel
        {
            get
            {
                return this.SeverityLevelField;
            }
            set
            {
                this.SeverityLevelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EVRentalWCFServiceReference.ICheckOutQuanNhSoapService")]
    public interface ICheckOutQuanNhSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/GetAll", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<EVRentalWCFServiceReference.CheckOutQuanNh[]> GetAllAsync();
        
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/GetReturnConditions", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/GetReturnConditionsResponse")]
    System.Threading.Tasks.Task<EVRentalWCFServiceReference.ReturnCondition[]> GetReturnConditionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/GetById", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<EVRentalWCFServiceReference.CheckOutQuanNh> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/Create", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(EVRentalWCFServiceReference.CheckOutQuanNh checkOutQuanNh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/Update", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(EVRentalWCFServiceReference.CheckOutQuanNh checkOutQuanNh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckOutQuanNhSoapService/Delete", ReplyAction="http://tempuri.org/ICheckOutQuanNhSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICheckOutQuanNhSoapServiceChannel : EVRentalWCFServiceReference.ICheckOutQuanNhSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CheckOutQuanNhSoapServiceClient : System.ServiceModel.ClientBase<EVRentalWCFServiceReference.ICheckOutQuanNhSoapService>, EVRentalWCFServiceReference.ICheckOutQuanNhSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CheckOutQuanNhSoapServiceClient() : 
                base(CheckOutQuanNhSoapServiceClient.GetDefaultBinding(), CheckOutQuanNhSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICheckOutQuanNhSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckOutQuanNhSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CheckOutQuanNhSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), CheckOutQuanNhSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckOutQuanNhSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CheckOutQuanNhSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckOutQuanNhSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CheckOutQuanNhSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckOutQuanNhSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EVRentalWCFServiceReference.CheckOutQuanNh[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<EVRentalWCFServiceReference.ReturnCondition[]> GetReturnConditionsAsync()
        {
            return base.Channel.GetReturnConditionsAsync();
        }
        
        public System.Threading.Tasks.Task<EVRentalWCFServiceReference.CheckOutQuanNh> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(EVRentalWCFServiceReference.CheckOutQuanNh checkOutQuanNh)
        {
            return base.Channel.CreateAsync(checkOutQuanNh);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(EVRentalWCFServiceReference.CheckOutQuanNh checkOutQuanNh)
        {
            return base.Channel.UpdateAsync(checkOutQuanNh);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICheckOutQuanNhSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICheckOutQuanNhSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7130/CheckOutQuanNhSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CheckOutQuanNhSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICheckOutQuanNhSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CheckOutQuanNhSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICheckOutQuanNhSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICheckOutQuanNhSoapService,
        }
    }
}
